import bcrypt from 'bcryptjs';
import {
  IUser,
  IDoctor,
  IHospital,
  IAppointment,
  IPayment,
  IReview,
  INotification,
  ISystemLog,
} from './types.ts';

// In-Memory persistent data store with full seed data and JSON syncing capability
class DatabaseStore {
  users: IUser[] = [];
  doctors: IDoctor[] = [];
  hospitals: IHospital[] = [];
  appointments: IAppointment[] = [];
  payments: IPayment[] = [];
  reviews: IReview[] = [];
  notifications: INotification[] = [];
  systemLogs: ISystemLog[] = [];
  businessSettings: {
    hospitalName: string;
    businessUpiId: string;
    bankName: string;
    accountHolderName: string;
    accountNumber: string;
    ifscCode: string;
    branch: string;
    razorpayKeyId?: string;
    isLiveRazorpayConfigured?: boolean;
  } = {
    hospitalName: 'Shakib Hospital',
    businessUpiId: 'shakib.hospital@okhdfcbank',
    bankName: 'HDFC Bank',
    accountHolderName: 'Shakib Healthcare Services Pvt Ltd',
    accountNumber: '50200012345678',
    ifscCode: 'HDFC0001234',
    branch: 'Medical Enclave, New Delhi',
    razorpayKeyId: process.env.RAZORPAY_KEY_ID || '',
    isLiveRazorpayConfigured: !!(process.env.RAZORPAY_KEY_ID && !process.env.RAZORPAY_KEY_ID.includes('demo') && !process.env.RAZORPAY_KEY_ID.includes('sample')),
  };

  constructor() {
    this.seedInitialData();
  }

  async seedInitialData() {
    const salt = await bcrypt.genSalt(10);
    const patientHash = await bcrypt.hash('Patient@123', salt);
    const doctorHash = await bcrypt.hash('Doctor@123', salt);
    const adminHash = await bcrypt.hash('Admin@123', salt);

    // 1. Initial Hospitals
    this.hospitals = [
      {
        _id: 'hosp_1',
        name: 'Shakib Super Speciality Hospital',
        image: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&w=800&q=80',
        description: 'JCI and NABH accredited premier multi-speciality tertiary healthcare institution equipped with cutting-edge robotic surgery suites, 24/7 cardiac emergency unit, and comprehensive diagnostic laboratories.',
        address: '21 Medical Enclave, Connaught Place',
        city: 'New Delhi',
        state: 'Delhi NCR',
        pincode: '110001',
        contact: {
          phone: '+91 11 2829 0200',
          emergency: '+91 11 1066',
          email: 'emergency@shakibhospital.demo',
        },
        departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'Oncology', 'Emergency'],
        facilities: ['24/7 Emergency & Trauma', 'Advanced ICU & NICU', 'Modular OT Suites', 'Robotic Surgery', 'In-house Pharmacy', 'Blood Bank', 'Ambulance GPS Dispatch'],
        rating: 4.9,
        totalReviews: 324,
        emergency24x7: true,
        totalBeds: 550,
        establishedYear: 1998,
        coordinates: { lat: 28.6304, lng: 77.2177 },
        createdAt: '2025-01-10T08:00:00.000Z',
      },
      {
        _id: 'hosp_2',
        name: 'Max Multi-Speciality Institute',
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
        description: 'World-class healthcare facility recognized for pioneering minimally invasive surgeries, organ transplant excellence, and compassionate specialized pediatric & neonatal care.',
        address: '1, 2 Press Enclave Marg, Saket',
        city: 'New Delhi',
        state: 'Delhi NCR',
        pincode: '110017',
        contact: {
          phone: '+91 11 2651 5050',
          emergency: '+91 11 4055 4055',
          email: 'care@maxsaket.demo',
        },
        departments: ['Cardiology', 'Dermatology', 'Neurology', 'Orthopedics', 'Gynecology', 'Dentistry'],
        facilities: ['Level 1 Trauma Center', 'PET-CT & 3T MRI', 'Cardiac Catheterization Lab', 'Digital Radiography', 'Valet Parking', 'International Patient Lounge'],
        rating: 4.8,
        totalReviews: 245,
        emergency24x7: true,
        totalBeds: 480,
        establishedYear: 1996,
        coordinates: { lat: 28.5284, lng: 77.2185 },
        createdAt: '2025-01-12T08:00:00.000Z',
      },
      {
        _id: 'hosp_3',
        name: 'Fortis Memorial Health City',
        image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&w=800&q=80',
        description: 'Next-generation hospital known for state-of-the-art neurosciences, orthopedic joint reconstruction, and dedicated clinical research departments.',
        address: 'Sector 44, Opposite HUDA City Centre',
        city: 'Gurugram',
        state: 'Haryana',
        pincode: '122002',
        contact: {
          phone: '+91 124 496 2200',
          emergency: '+91 124 1050',
          email: 'support@fortisgurugram.demo',
        },
        departments: ['Orthopedics', 'Neurology', 'General Medicine', 'ENT', 'Pediatrics'],
        facilities: ['Dedicated Stroke Unit', 'Sports Medicine & Rehab', 'Automated Lab Systems', 'Helipad Access', 'Private Suites'],
        rating: 4.7,
        totalReviews: 189,
        emergency24x7: true,
        totalBeds: 380,
        establishedYear: 2004,
        coordinates: { lat: 28.4595, lng: 77.0725 },
        createdAt: '2025-01-15T08:00:00.000Z',
      },
      {
        _id: 'hosp_4',
        name: 'Manipal Super-Care Hospital',
        image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=800&q=80',
        description: 'Comprehensive tertiary healthcare provider with dedicated departments for high-risk obstetrics, clinical cardiology, and comprehensive aesthetic & medical dermatology.',
        address: '98 HAL Old Airport Road, Kodihalli',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560017',
        contact: {
          phone: '+91 80 2502 4444',
          emergency: '+91 80 2222 1111',
          email: 'info@manipalblr.demo',
        },
        departments: ['Gynecology', 'Cardiology', 'Dermatology', 'General Medicine', 'Dentistry'],
        facilities: ['24/7 Neonatal ICU', 'Dialysis Center', 'Comprehensive Chemotherapy Center', 'Endoscopy Suites', 'Cafeteria & Wellness Hub'],
        rating: 4.8,
        totalReviews: 210,
        emergency24x7: true,
        totalBeds: 600,
        establishedYear: 1991,
        coordinates: { lat: 12.9592, lng: 77.6499 },
        createdAt: '2025-01-18T08:00:00.000Z',
      },
      {
        _id: 'hosp_5',
        name: 'Kokilaben Dhirubhai Ambani Hospital',
        image: 'https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?auto=format&fit=crop&w=800&q=80',
        description: 'Multi-specialty quaternary care hospital offering premier robotic joint replacement, advanced epilepsy monitoring, and pediatric cardiac surgery programs.',
        address: 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400053',
        contact: {
          phone: '+91 22 4269 6969',
          emergency: '+91 22 4269 9999',
          email: 'contact@kokilabenhospital.demo',
        },
        departments: ['Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'Dermatology', 'ENT'],
        facilities: ['Intra-operative MRI', 'da Vinci Robotic Surgery System', 'Gait & Motion Analysis Lab', '24/7 Pharmacy', 'Air Ambulance Coordination'],
        rating: 4.9,
        totalReviews: 412,
        emergency24x7: true,
        totalBeds: 750,
        establishedYear: 2009,
        coordinates: { lat: 19.1311, lng: 72.8258 },
        createdAt: '2025-01-20T08:00:00.000Z',
      },
      {
        _id: 'hosp_6',
        name: 'Ruby Hall Clinic & Research Center',
        image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
        description: 'Leading healthcare landmark renowned for organ transplantation, oncology therapies, preventive cardiology, and 24-hour trauma support.',
        address: '40 Sassoon Road, Near Pune Railway Station',
        city: 'Pune',
        state: 'Maharashtra',
        pincode: '411001',
        contact: {
          phone: '+91 20 6645 5100',
          emergency: '+91 20 2616 3399',
          email: 'care@rubyhallpune.demo',
        },
        departments: ['Cardiology', 'General Medicine', 'Orthopedics', 'ENT', 'Dentistry'],
        facilities: ['Linear Accelerator Unit', 'Cardiac Rehabilitation', 'Emergency Stroke Response', 'Tele-consultation Hub'],
        rating: 4.6,
        totalReviews: 175,
        emergency24x7: true,
        totalBeds: 500,
        establishedYear: 1959,
        coordinates: { lat: 18.5298, lng: 73.8744 },
        createdAt: '2025-01-22T08:00:00.000Z',
      }
    ];

    // 2. Initial Users
    this.users = [
      {
        _id: 'usr_admin',
        name: 'Super Administrator',
        email: 'admin@example.com',
        phone: '+91 98765 00001',
        password: adminHash,
        role: 'admin',
        profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1985-04-12',
        gender: 'Female',
        address: 'MediCare HQ, Medical Square',
        city: 'New Delhi',
        isBlocked: false,
        createdAt: '2025-01-01T00:00:00.000Z',
      },
      {
        _id: 'usr_patient',
        name: 'Aman Shakib',
        email: 'patient@example.com',
        phone: '+91 98765 12345',
        password: patientHash,
        role: 'patient',
        profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '2001-08-15',
        gender: 'Male',
        address: 'B-402, Sunshine Heights, Viman Nagar',
        city: 'Pune',
        isBlocked: false,
        createdAt: '2025-01-05T10:00:00.000Z',
      },
      {
        _id: 'usr_patient2',
        name: 'Sneha Kulkarni',
        email: 'sneha.k@example.com',
        phone: '+91 98220 54321',
        password: patientHash,
        role: 'patient',
        profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1995-11-20',
        gender: 'Female',
        address: 'Plot 12, Baner Park Road',
        city: 'Pune',
        isBlocked: false,
        createdAt: '2025-01-10T12:00:00.000Z',
      },
      {
        _id: 'usr_doc1',
        name: 'Dr. Rahul Sharma',
        email: 'doctor@example.com',
        phone: '+91 98111 22233',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1978-06-22',
        gender: 'Male',
        address: 'Flat 12B, Apollo Doctors Enclave',
        city: 'Chennai',
        isBlocked: false,
        createdAt: '2025-01-08T09:00:00.000Z',
      },
      {
        _id: 'usr_doc2',
        name: 'Dr. Priya Patel',
        email: 'priya.patel@example.com',
        phone: '+91 98222 33344',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1594824813620-424a1b0266bf?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1984-03-14',
        gender: 'Female',
        address: 'Saket Doctors Colony',
        city: 'New Delhi',
        isBlocked: false,
        createdAt: '2025-01-10T09:00:00.000Z',
      },
      {
        _id: 'usr_doc3',
        name: 'Dr. Vikram Malhotra',
        email: 'vikram.m@example.com',
        phone: '+91 98333 44455',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1975-09-05',
        gender: 'Male',
        address: 'Indiranagar 100ft Road',
        city: 'Bengaluru',
        isBlocked: false,
        createdAt: '2025-01-12T09:00:00.000Z',
      },
      {
        _id: 'usr_doc4',
        name: 'Dr. Ananya Sen',
        email: 'ananya.sen@example.com',
        phone: '+91 98444 55566',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1988-12-01',
        gender: 'Female',
        address: 'Juhu Tara Road',
        city: 'Mumbai',
        isBlocked: false,
        createdAt: '2025-01-14T09:00:00.000Z',
      },
      {
        _id: 'usr_doc5',
        name: 'Dr. Rajesh Verma',
        email: 'rajesh.verma@example.com',
        phone: '+91 98555 66677',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1980-02-18',
        gender: 'Male',
        address: 'Golf Course Extension Road',
        city: 'Gurugram',
        isBlocked: false,
        createdAt: '2025-01-15T09:00:00.000Z',
      },
      {
        _id: 'usr_doc6',
        name: 'Dr. Meera Nambiar',
        email: 'meera.nambiar@example.com',
        phone: '+91 98666 77788',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1623854767648-e7bb8009f0db?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1986-07-28',
        gender: 'Female',
        address: 'Aundh Medical Heights',
        city: 'Pune',
        isBlocked: false,
        createdAt: '2025-01-16T09:00:00.000Z',
      },
      {
        _id: 'usr_doc7',
        name: 'Dr. Arjun Kapoor',
        email: 'arjun.kapoor@example.com',
        phone: '+91 98777 88899',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1982-10-10',
        gender: 'Male',
        address: 'Anna Nagar West',
        city: 'Chennai',
        isBlocked: false,
        createdAt: '2025-01-18T09:00:00.000Z',
      },
      {
        _id: 'usr_doc8',
        name: 'Dr. Sunita Deshmukh',
        email: 'sunita.deshmukh@example.com',
        phone: '+91 98888 99900',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1979-05-04',
        gender: 'Female',
        address: 'Koregaon Park Main Road',
        city: 'Pune',
        isBlocked: false,
        createdAt: '2025-01-20T09:00:00.000Z',
      },
      {
        _id: 'usr_doc9',
        name: 'Dr. Rohan Mehra',
        email: 'rohan.mehra@example.com',
        phone: '+91 98999 11122',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1990-08-30',
        gender: 'Male',
        address: 'Hauz Khas Enclave',
        city: 'New Delhi',
        isBlocked: false,
        createdAt: '2025-01-22T09:00:00.000Z',
      },
      {
        _id: 'usr_doc10',
        name: 'Dr. Fatima Khan',
        email: 'fatima.khan@example.com',
        phone: '+91 98123 45678',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1987-04-19',
        gender: 'Female',
        address: 'Koramangala 4th Block',
        city: 'Bengaluru',
        isBlocked: false,
        createdAt: '2025-01-24T09:00:00.000Z',
      },
      {
        _id: 'usr_doc11',
        name: 'Dr. Deepak Chatterjee',
        email: 'deepak.c@example.com',
        phone: '+91 98234 56789',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1981-01-15',
        gender: 'Male',
        address: 'Bandra Reclamation',
        city: 'Mumbai',
        isBlocked: false,
        createdAt: '2025-01-25T09:00:00.000Z',
      },
      {
        _id: 'usr_doc12',
        name: 'Dr. Nandini Roy (Pending Approval)',
        email: 'nandini.roy@example.com',
        phone: '+91 98345 67890',
        password: doctorHash,
        role: 'doctor',
        profileImage: 'https://images.unsplash.com/photo-1594824813620-424a1b0266bf?auto=format&fit=crop&w=400&q=80',
        dateOfBirth: '1992-09-12',
        gender: 'Female',
        address: 'DLF Phase 5',
        city: 'Gurugram',
        isBlocked: false,
        createdAt: '2025-02-01T09:00:00.000Z',
      }
    ];

    // 3. Initial Doctors Profiles
    this.doctors = [
      {
        _id: 'doc_1',
        userId: 'usr_doc1',
        name: 'Dr. Rahul Sharma',
        email: 'doctor@example.com',
        phone: '+91 98111 22233',
        profileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
        specialization: 'Cardiology',
        qualification: 'MBBS, MD (General Medicine), DM (Cardiology), FACC',
        experience: 18,
        registrationNumber: 'MCI-TN-2007-44912',
        hospitalId: 'hosp_1',
        hospitalName: 'Shakib Super Speciality Hospital',
        consultationFee: 800,
        about: 'Senior Interventional Cardiologist with over 18 years of clinical expertise in coronary angioplasty, transcatheter aortic valve implantation (TAVI), heart failure management, and preventive cardiovascular care.',
        languages: ['English', 'Hindi', 'Tamil'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '09:00', end: '17:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:00', end: '14:00' },
        rating: 4.9,
        totalReviews: 128,
        approvalStatus: 'approved',
        featured: true,
        createdAt: '2025-01-08T09:30:00.000Z',
      },
      {
        _id: 'doc_2',
        userId: 'usr_doc2',
        name: 'Dr. Priya Patel',
        email: 'priya.patel@example.com',
        phone: '+91 98222 33344',
        profileImage: 'https://images.unsplash.com/photo-1594824813620-424a1b0266bf?auto=format&fit=crop&w=400&q=80',
        specialization: 'Pediatrics',
        qualification: 'MBBS, DCH, DNB (Pediatrics), Fellowship in Neonatology',
        experience: 12,
        registrationNumber: 'DMC-DL-2012-78190',
        hospitalId: 'hosp_2',
        hospitalName: 'Max Multi-Speciality Institute',
        consultationFee: 650,
        about: 'Dedicated pediatrician and child health specialist known for gentle compassionate care in newborn developmental assessment, adolescent wellness, childhood asthma, and pediatric immunization schedules.',
        languages: ['English', 'Hindi', 'Gujarati'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        workingHours: { start: '10:00', end: '18:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:30', end: '14:30' },
        rating: 4.9,
        totalReviews: 94,
        approvalStatus: 'approved',
        featured: true,
        createdAt: '2025-01-10T09:30:00.000Z',
      },
      {
        _id: 'doc_3',
        userId: 'usr_doc3',
        name: 'Dr. Vikram Malhotra',
        email: 'vikram.m@example.com',
        phone: '+91 98333 44455',
        profileImage: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
        specialization: 'Neurology',
        qualification: 'MBBS, MD (Medicine), DM (Neurology), FINR',
        experience: 20,
        registrationNumber: 'KMC-KA-2004-12903',
        hospitalId: 'hosp_4',
        hospitalName: 'Manipal Super-Care Hospital',
        consultationFee: 1000,
        about: 'Internationally trained consultant neurologist with extensive research in acute stroke thrombolysis, epilepsy syndromes, Parkinson’s disease management, migraine diagnostics, and neuromuscular disorders.',
        languages: ['English', 'Hindi', 'Kannada'],
        availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '09:30', end: '16:30' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:00', end: '14:00' },
        rating: 4.8,
        totalReviews: 87,
        approvalStatus: 'approved',
        featured: true,
        createdAt: '2025-01-12T09:30:00.000Z',
      },
      {
        _id: 'doc_4',
        userId: 'usr_doc4',
        name: 'Dr. Ananya Sen',
        email: 'ananya.sen@example.com',
        phone: '+91 98444 55566',
        profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
        specialization: 'Dermatology',
        qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
        experience: 9,
        registrationNumber: 'MMC-MH-2015-66721',
        hospitalId: 'hosp_5',
        hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
        consultationFee: 750,
        about: 'Clinical & Aesthetic Dermatologist specializing in laser treatments, stubborn acne protocols, autoimmune skin disorders, hair restoration therapies, and customized anti-aging regimes.',
        languages: ['English', 'Hindi', 'Bengali', 'Marathi'],
        availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '11:00', end: '19:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '14:00', end: '15:00' },
        rating: 4.9,
        totalReviews: 112,
        approvalStatus: 'approved',
        featured: true,
        createdAt: '2025-01-14T09:30:00.000Z',
      },
      {
        _id: 'doc_5',
        userId: 'usr_doc5',
        name: 'Dr. Rajesh Verma',
        email: 'rajesh.verma@example.com',
        phone: '+91 98555 66677',
        profileImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
        specialization: 'Orthopedics',
        qualification: 'MBBS, MS (Orthopedics), MCh (Joint Replacement)',
        experience: 16,
        registrationNumber: 'HNMC-HR-2008-33821',
        hospitalId: 'hosp_3',
        hospitalName: 'Fortis Memorial Health City',
        consultationFee: 900,
        about: 'Chief Orthopedic Surgeon specializing in computer-navigated total knee and hip replacements, arthroscopic sports injury reconstruction, spinal disc therapies, and complex fracture management.',
        languages: ['English', 'Hindi', 'Punjabi'],
        availableDays: ['Monday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '09:00', end: '17:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:00', end: '14:00' },
        rating: 4.8,
        totalReviews: 76,
        approvalStatus: 'approved',
        featured: false,
        createdAt: '2025-01-15T09:30:00.000Z',
      },
      {
        _id: 'doc_6',
        userId: 'usr_doc6',
        name: 'Dr. Meera Nambiar',
        email: 'meera.nambiar@example.com',
        phone: '+91 98666 77788',
        profileImage: 'https://images.unsplash.com/photo-1623854767648-e7bb8009f0db?auto=format&fit=crop&w=400&q=80',
        specialization: 'Gynecology',
        qualification: 'MBBS, MS (Obstetrics & Gynecology), FMAS',
        experience: 14,
        registrationNumber: 'MMC-MH-2010-44991',
        hospitalId: 'hosp_6',
        hospitalName: 'Ruby Hall Clinic & Research Center',
        consultationFee: 700,
        about: 'Senior Consultant Obstetrician and Laparoscopic Gynecologist focusing on high-risk pregnancies, PCOS/PCOD holistic management, infertility consultations, and painless natural birthing protocols.',
        languages: ['English', 'Hindi', 'Malayalam', 'Marathi'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday'],
        workingHours: { start: '09:30', end: '17:30' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:30', end: '14:30' },
        rating: 4.9,
        totalReviews: 105,
        approvalStatus: 'approved',
        featured: true,
        createdAt: '2025-01-16T09:30:00.000Z',
      },
      {
        _id: 'doc_7',
        userId: 'usr_doc7',
        name: 'Dr. Arjun Kapoor',
        email: 'arjun.kapoor@example.com',
        phone: '+91 98777 88899',
        profileImage: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
        specialization: 'ENT',
        qualification: 'MBBS, MS (ENT - Otorhinolaryngology)',
        experience: 11,
        registrationNumber: 'MCI-TN-2013-88219',
        hospitalId: 'hosp_1',
        hospitalName: 'Apollo Super Speciality Hospital',
        consultationFee: 600,
        about: 'Consultant ENT & Head-Neck Surgeon skilled in endoscopic sinus surgery, micro-ear surgical procedures, hearing aid evaluation, sleep apnea treatment, and pediatric voice disorders.',
        languages: ['English', 'Hindi', 'Tamil'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        workingHours: { start: '10:00', end: '17:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:00', end: '14:00' },
        rating: 4.7,
        totalReviews: 62,
        approvalStatus: 'approved',
        featured: false,
        createdAt: '2025-01-18T09:30:00.000Z',
      },
      {
        _id: 'doc_8',
        userId: 'usr_doc8',
        name: 'Dr. Sunita Deshmukh',
        email: 'sunita.deshmukh@example.com',
        phone: '+91 98888 99900',
        profileImage: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80',
        specialization: 'General Medicine',
        qualification: 'MBBS, MD (Internal Medicine), FACP',
        experience: 22,
        registrationNumber: 'MMC-MH-2002-11002',
        hospitalId: 'hosp_6',
        hospitalName: 'Ruby Hall Clinic & Research Center',
        consultationFee: 500,
        about: 'Senior Consultant Physician providing comprehensive diagnosis and management of chronic diabetes mellitus, hypertension, thyroid conditions, metabolic syndrome, and infectious fevers.',
        languages: ['English', 'Hindi', 'Marathi'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '09:00', end: '18:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:00', end: '14:00' },
        rating: 4.8,
        totalReviews: 140,
        approvalStatus: 'approved',
        featured: false,
        createdAt: '2025-01-20T09:30:00.000Z',
      },
      {
        _id: 'doc_9',
        userId: 'usr_doc9',
        name: 'Dr. Rohan Mehra',
        email: 'rohan.mehra@example.com',
        phone: '+91 98999 11122',
        profileImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=400&q=80',
        specialization: 'Dentistry',
        qualification: 'BDS, MDS (Prosthodontics & Implantology)',
        experience: 8,
        registrationNumber: 'DCI-DL-2016-55443',
        hospitalId: 'hosp_2',
        hospitalName: 'Max Multi-Speciality Institute',
        consultationFee: 500,
        about: 'Cosmetic Dentist and Implantologist offering painless single-sitting root canals, invisible aligners, dental crowns, teeth whitening, smile redesigning, and pediatric dental hygiene.',
        languages: ['English', 'Hindi'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Saturday'],
        workingHours: { start: '10:00', end: '19:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '14:00', end: '15:00' },
        rating: 4.7,
        totalReviews: 53,
        approvalStatus: 'approved',
        featured: false,
        createdAt: '2025-01-22T09:30:00.000Z',
      },
      {
        _id: 'doc_10',
        userId: 'usr_doc10',
        name: 'Dr. Fatima Khan',
        email: 'fatima.khan@example.com',
        phone: '+91 98123 45678',
        profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
        specialization: 'Cardiology',
        qualification: 'MBBS, MD (Medicine), DM (Cardiology)',
        experience: 10,
        registrationNumber: 'KMC-KA-2014-99881',
        hospitalId: 'hosp_4',
        hospitalName: 'Manipal Super-Care Hospital',
        consultationFee: 750,
        about: 'Non-invasive and Preventive Cardiologist specializing in 3D echocardiography, stress echo tests, cardiac rehabilitation for post-bypass patients, and lipid disorders management.',
        languages: ['English', 'Hindi', 'Urdu', 'Kannada'],
        availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
        workingHours: { start: '09:00', end: '16:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '12:30', end: '13:30' },
        rating: 4.8,
        totalReviews: 48,
        approvalStatus: 'approved',
        featured: false,
        createdAt: '2025-01-24T09:30:00.000Z',
      },
      {
        _id: 'doc_11',
        userId: 'usr_doc11',
        name: 'Dr. Deepak Chatterjee',
        email: 'deepak.c@example.com',
        phone: '+91 98234 56789',
        profileImage: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&w=400&q=80',
        specialization: 'Orthopedics',
        qualification: 'MBBS, MS (Ortho), Fellowship in Spine Surgery',
        experience: 15,
        registrationNumber: 'MMC-MH-2009-88334',
        hospitalId: 'hosp_5',
        hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
        consultationFee: 850,
        about: 'Spine and Orthopedic Surgeon treating herniated discs, scoliosis, spinal stenosis, sciatica nerve decompression, and minimally invasive keyhole spinal surgeries.',
        languages: ['English', 'Hindi', 'Marathi', 'Bengali'],
        availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
        workingHours: { start: '10:00', end: '18:00' },
        slotDurationMinutes: 30,
        breakTime: { start: '13:30', end: '14:30' },
        rating: 4.9,
        totalReviews: 69,
        approvalStatus: 'approved',
        featured: false,
        createdAt: '2025-01-25T09:30:00.000Z',
      },
      {
        _id: 'doc_12',
        userId: 'usr_doc12',
        name: 'Dr. Nandini Roy',
        email: 'nandini.roy@example.com',
        phone: '+91 98345 67890',
        profileImage: 'https://images.unsplash.com/photo-1594824813620-424a1b0266bf?auto=format&fit=crop&w=400&q=80',
        specialization: 'Dermatology',
        qualification: 'MBBS, DVD (Dermatology)',
        experience: 6,
        registrationNumber: 'HNMC-HR-2018-99211',
        hospitalId: 'hosp_3',
        hospitalName: 'Fortis Memorial Health City',
        consultationFee: 600,
        about: 'Dermatologist with special focus on eczema, psoriasis biologics, chemical peels, and pediatric skin rashes.',
        languages: ['English', 'Hindi'],
        availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        workingHours: { start: '10:00', end: '17:00' },
        slotDurationMinutes: 30,
        rating: 5.0,
        totalReviews: 0,
        approvalStatus: 'pending', // Pending Admin Approval
        featured: false,
        createdAt: '2025-02-01T09:30:00.000Z',
      }
    ];

    // 4. Initial Appointments
    const today = new Date().toISOString().split('T')[0];
    const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
    const dayAfterTomorrow = new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0];
    const pastDate1 = '2025-02-10';
    const pastDate2 = '2025-02-15';

    this.appointments = [
      {
        _id: 'apt_1001',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        patientEmail: 'patient@example.com',
        patientPhone: '+91 98765 12345',
        patientGender: 'Male',
        patientAge: 24,
        doctorId: 'doc_1',
        doctorName: 'Dr. Rahul Sharma',
        doctorSpecialization: 'Cardiology',
        doctorProfileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
        hospitalId: 'hosp_1',
        hospitalName: 'Apollo Super Speciality Hospital',
        appointmentDate: tomorrow,
        appointmentTime: '10:30 AM',
        amount: 800,
        paymentStatus: 'paid',
        appointmentStatus: 'confirmed',
        paymentId: 'pay_rzp_9901824',
        orderId: 'order_MC9901824',
        reason: 'Routine annual cardiovascular checkup & mild chest tightness during heavy workouts.',
        patientNotes: 'Family history of hypertension. Attached latest ECG summary.',
        createdAt: '2025-02-18T10:15:00.000Z',
        updatedAt: '2025-02-18T10:18:00.000Z',
      },
      {
        _id: 'apt_1002',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        patientEmail: 'patient@example.com',
        patientPhone: '+91 98765 12345',
        patientGender: 'Male',
        patientAge: 24,
        doctorId: 'doc_4',
        doctorName: 'Dr. Ananya Sen',
        doctorSpecialization: 'Dermatology',
        doctorProfileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
        hospitalId: 'hosp_5',
        hospitalName: 'Kokilaben Dhirubhai Ambani Hospital',
        appointmentDate: dayAfterTomorrow,
        appointmentTime: '02:30 PM',
        amount: 750,
        paymentStatus: 'paid',
        appointmentStatus: 'upcoming',
        paymentId: 'pay_rzp_9901992',
        orderId: 'order_MC9901992',
        reason: 'Persistent skin allergy and dry patches on forearms after swimming.',
        patientNotes: 'Started about two weeks ago.',
        createdAt: '2025-02-19T14:30:00.000Z',
        updatedAt: '2025-02-19T14:35:00.000Z',
      },
      {
        _id: 'apt_1003',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        patientEmail: 'patient@example.com',
        patientPhone: '+91 98765 12345',
        patientGender: 'Male',
        patientAge: 24,
        doctorId: 'doc_8',
        doctorName: 'Dr. Sunita Deshmukh',
        doctorSpecialization: 'General Medicine',
        doctorProfileImage: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80',
        hospitalId: 'hosp_6',
        hospitalName: 'Ruby Hall Clinic & Research Center',
        appointmentDate: pastDate1,
        appointmentTime: '11:00 AM',
        amount: 500,
        paymentStatus: 'paid',
        appointmentStatus: 'completed',
        paymentId: 'pay_rzp_8871234',
        orderId: 'order_MC8871234',
        reason: 'Seasonal viral flu and mild bronchitis with sore throat.',
        consultationNotes: 'Vitals stable. Temp 98.4F, BP 120/80. Mild pharyngeal congestion noted. Advised warm saline gargles, hydration and 5-day course of prescribed medication.',
        prescription: '1. Tab Azithromycin 500mg (1 OD x 3 days)\n2. Tab Paracetamol 650mg SOS\n3. Levocetirizine 5mg (1 HS x 5 days)\n4. Adequate hydration & rest.',
        createdAt: '2025-02-09T08:20:00.000Z',
        updatedAt: '2025-02-10T11:45:00.000Z',
      },
      {
        _id: 'apt_1004',
        patientId: 'usr_patient2',
        patientName: 'Sneha Kulkarni',
        patientEmail: 'sneha.k@example.com',
        patientPhone: '+91 98220 54321',
        patientGender: 'Female',
        patientAge: 29,
        doctorId: 'doc_1',
        doctorName: 'Dr. Rahul Sharma',
        doctorSpecialization: 'Cardiology',
        doctorProfileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
        hospitalId: 'hosp_1',
        hospitalName: 'Apollo Super Speciality Hospital',
        appointmentDate: pastDate2,
        appointmentTime: '03:00 PM',
        amount: 800,
        paymentStatus: 'paid',
        appointmentStatus: 'completed',
        paymentId: 'pay_rzp_7761299',
        orderId: 'order_MC7761299',
        reason: 'Palpitations during stressful work periods and high caffeine intake.',
        consultationNotes: '2D Echocardiogram normal. Sinus rhythm confirmed. Advised reducing caffeine to 1 cup/day and 20 mins brisk morning walk.',
        prescription: '1. Tab Metoprolol 25mg (1 OD morning x 14 days)\n2. Lifestyle modification guide provided.',
        createdAt: '2025-02-14T11:00:00.000Z',
        updatedAt: '2025-02-15T15:40:00.000Z',
      },
      {
        _id: 'apt_1005',
        patientId: 'usr_patient2',
        patientName: 'Sneha Kulkarni',
        patientEmail: 'sneha.k@example.com',
        patientPhone: '+91 98220 54321',
        patientGender: 'Female',
        patientAge: 29,
        doctorId: 'doc_6',
        doctorName: 'Dr. Meera Nambiar',
        doctorSpecialization: 'Gynecology',
        doctorProfileImage: 'https://images.unsplash.com/photo-1623854767648-e7bb8009f0db?auto=format&fit=crop&w=400&q=80',
        hospitalId: 'hosp_6',
        hospitalName: 'Ruby Hall Clinic & Research Center',
        appointmentDate: today,
        appointmentTime: '11:30 AM',
        amount: 700,
        paymentStatus: 'paid',
        appointmentStatus: 'confirmed',
        paymentId: 'pay_rzp_6655441',
        orderId: 'order_MC6655441',
        reason: 'PCOS follow up and hormonal panel review.',
        patientNotes: 'Fasting reports ready.',
        createdAt: '2025-02-20T09:00:00.000Z',
        updatedAt: '2025-02-20T09:05:00.000Z',
      }
    ];

    // 5. Initial Payments
    this.payments = [
      {
        _id: 'pay_1',
        appointmentId: 'apt_1001',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        amount: 800,
        paymentGateway: 'Razorpay',
        transactionId: 'pay_rzp_9901824',
        orderId: 'order_MC9901824',
        status: 'paid',
        method: 'UPI (GooglePay / UPI ID: aman@oksbi)',
        createdAt: '2025-02-18T10:18:00.000Z',
      },
      {
        _id: 'pay_2',
        appointmentId: 'apt_1002',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        amount: 750,
        paymentGateway: 'Razorpay',
        transactionId: 'pay_rzp_9901992',
        orderId: 'order_MC9901992',
        status: 'paid',
        method: 'Credit Card (Visa ending in 4022)',
        createdAt: '2025-02-19T14:35:00.000Z',
      },
      {
        _id: 'pay_3',
        appointmentId: 'apt_1003',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        amount: 500,
        paymentGateway: 'Razorpay',
        transactionId: 'pay_rzp_8871234',
        orderId: 'order_MC8871234',
        status: 'paid',
        method: 'Net Banking (HDFC Bank)',
        createdAt: '2025-02-09T08:25:00.000Z',
      },
      {
        _id: 'pay_4',
        appointmentId: 'apt_1004',
        patientId: 'usr_patient2',
        patientName: 'Sneha Kulkarni',
        amount: 800,
        paymentGateway: 'Razorpay',
        transactionId: 'pay_rzp_7761299',
        orderId: 'order_MC7761299',
        status: 'paid',
        method: 'UPI (PhonePe)',
        createdAt: '2025-02-14T11:05:00.000Z',
      },
      {
        _id: 'pay_5',
        appointmentId: 'apt_1005',
        patientId: 'usr_patient2',
        patientName: 'Sneha Kulkarni',
        amount: 700,
        paymentGateway: 'Razorpay',
        transactionId: 'pay_rzp_6655441',
        orderId: 'order_MC6655441',
        status: 'paid',
        method: 'Debit Card (Mastercard ending in 8812)',
        createdAt: '2025-02-20T09:05:00.000Z',
      }
    ];

    // 6. Initial Reviews
    this.reviews = [
      {
        _id: 'rev_1',
        patientId: 'usr_patient',
        patientName: 'Aman Shakib',
        patientImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
        doctorId: 'doc_8',
        appointmentId: 'apt_1003',
        rating: 5,
        comment: 'Dr. Sunita Deshmukh was exceptionally thorough and polite. She listened patiently to all my symptoms, explained why specific medications were necessary, and followed up promptly. Highly recommended!',
        createdAt: '2025-02-10T16:00:00.000Z',
      },
      {
        _id: 'rev_2',
        patientId: 'usr_patient2',
        patientName: 'Sneha Kulkarni',
        patientImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
        doctorId: 'doc_1',
        appointmentId: 'apt_1004',
        rating: 5,
        comment: 'Dr. Rahul Sharma is one of the most reassuring cardiologists I have consulted. The clinic at Apollo Hospital was very organized with virtually zero wait time.',
        createdAt: '2025-02-16T10:30:00.000Z',
      },
      {
        _id: 'rev_3',
        patientId: 'usr_patient',
        patientName: 'Rohit Verma',
        patientImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        doctorId: 'doc_2',
        appointmentId: 'apt_sample_old',
        rating: 5,
        comment: 'Dr. Priya Patel made my 4-year-old completely comfortable throughout the vaccination and checkup. Wonderful doctor and great clinic environment.',
        createdAt: '2025-02-12T11:20:00.000Z',
      },
      {
        _id: 'rev_4',
        patientId: 'usr_patient2',
        patientName: 'Kavita Joshi',
        patientImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
        doctorId: 'doc_4',
        appointmentId: 'apt_sample_old2',
        rating: 5,
        comment: 'Excellent dermatology advice from Dr. Ananya Sen! Clear diagnosis and my skin responded noticeably within 10 days.',
        createdAt: '2025-02-15T18:00:00.000Z',
      }
    ];

    // 7. Initial Notifications
    this.notifications = [
      {
        _id: 'notif_1',
        userId: 'usr_patient',
        title: 'Appointment Confirmed',
        message: 'Your appointment with Dr. Rahul Sharma on ' + tomorrow + ' at 10:30 AM has been confirmed.',
        type: 'appointment',
        link: '/dashboard',
        isRead: false,
        createdAt: '2025-02-18T10:18:00.000Z',
      },
      {
        _id: 'notif_2',
        userId: 'usr_patient',
        title: 'Payment Successful',
        message: 'Payment of ₹800 was received successfully. Receipt #MC9901824 is ready for download.',
        type: 'payment',
        link: '/dashboard',
        isRead: true,
        createdAt: '2025-02-18T10:18:00.000Z',
      },
      {
        _id: 'notif_3',
        userId: 'usr_doc1',
        title: 'New Appointment Booked',
        message: 'Patient Aman Shakib booked an appointment for ' + tomorrow + ' at 10:30 AM.',
        type: 'appointment',
        link: '/doctor/dashboard',
        isRead: false,
        createdAt: '2025-02-18T10:18:00.000Z',
      },
      {
        _id: 'notif_4',
        userId: 'usr_admin',
        title: 'New Doctor Verification Request',
        message: 'Dr. Nandini Roy registered and is awaiting credentials verification.',
        type: 'doctor',
        link: '/admin/doctors',
        isRead: false,
        createdAt: '2025-02-01T09:30:00.000Z',
      }
    ];

    // 8. Initial System Logs
    this.systemLogs = [
      {
        _id: 'log_1',
        action: 'DOCTOR_REGISTRATION',
        actor: 'Dr. Nandini Roy',
        role: 'doctor',
        details: 'Submitted MCI registration verification documents for Dermatology.',
        timestamp: '2025-02-01T09:30:00.000Z',
      },
      {
        _id: 'log_2',
        action: 'PAYMENT_PROCESSED',
        actor: 'Aman Shakib',
        role: 'patient',
        details: 'Payment of ₹800 via Razorpay Test Gateway (UPI) verified for Appointment #apt_1001.',
        timestamp: '2025-02-18T10:18:00.000Z',
      },
      {
        _id: 'log_3',
        action: 'EMAIL_DISPATCHED',
        actor: 'SYSTEM',
        role: 'system',
        details: 'Confirmation email simulated & dispatched to patient@example.com with receipt payload.',
        timestamp: '2025-02-18T10:18:05.000Z',
      }
    ];
  }

  // Helper Methods for Data Operations
  addNotification(userId: string, title: string, message: string, type: INotification['type'], link?: string) {
    const notif: INotification = {
      _id: 'notif_' + Date.now() + '_' + Math.random().toString(36).substr(2, 4),
      userId,
      title,
      message,
      type,
      link: link || '/dashboard',
      isRead: false,
      createdAt: new Date().toISOString(),
    };
    this.notifications.unshift(notif);
    return notif;
  }

  logAction(action: string, actor: string, role: string, details: string) {
    const log: ISystemLog = {
      _id: 'log_' + Date.now(),
      action,
      actor,
      role,
      details,
      timestamp: new Date().toISOString(),
    };
    this.systemLogs.unshift(log);
  }
}

export const db = new DatabaseStore();
